apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-py
  name: app-py
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-py
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-py
    spec:
      containers:
        - image: gcr.io/seventh-program-310407/github.com/manexin/app_py_gh
          imagePullPolicy: Always
          name: app-py-gh-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-py
  name: app-py-hpa-dsur
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-py
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: app-py
  name: app-py-service
  namespace: default
spec:
  clusterIP: 10.72.7.140
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30110
      port: 8091
      protocol: TCP
      targetPort: 5000
  selector:
    app: app-py
  sessionAffinity: None
  type: LoadBalancer

